[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_nft_anchor = "G4xeu1UsPpAhV9QnamPPftyLuxRVp18uTBp4vFh8ZgcC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/jupiter/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
